### ISSUE TITLE
Proper build script and/or system

### ISSUE THREAD

**Issue by countgizmo** [6D65/shovelleros#2]
Either create a shell script to support Linux and Mac OS X (and other *nix friendly environments) or choose a proper build system. There should be something to build JavaScript projects with dependencies, targets, etc.

**Comment by 6D65** [comment]
Working on that. Currently finishing up the vagrant file, for a clean development environment. Then will add a build system.

**Comment by 6D65** [comment]
Ran into some issues with the cocos2dx build script for linux, which doesn't work correctly with github, had to update it. Also, there's the issue with their cmakelists file. I have a feeling it will take a lot longer than i thought, even though there's a fair amount of progress on this.

Commited the current progress on this one defb8a85bd1040b850218687594882447d5a87d1. Still nothing works.

**Comment by 6D65** [comment]
Still having some issues with the cocos2d's build script, though we're getting closer to having something working. Will look into the cmake issue.

**Comment by 6D65** [comment]
Got it to work, but is taking a long ass time, currently cleaning it up and and optimizing a little bit, and instead of 3+ hours, it would take it less than 1 to setup, and work.

Actually my idea was bad, need to think of something else. Meanwhile we could just use the slow script, will give it a try a few more times to make sure it works though.

**Comment by 6D65** [comment]
First thing you'll want to have a local copy of the cocos vagrant box.
This command should download a local copy of it, it requires about 4.5GB of space. Based on this image you'll be able to launch/create the vagrant box with the shovellers downloaded/configured.

``` bash
vagrant box add cocosdev https://www.dropbox.com/s/7kpnnlt1qxjiibk/cocosdev_base.box?dl=1
```

**Comment by 6D65** [comment]
Using a small Debian box instead of the Ubuntu box turns out to be a pain. Still can't find a way to install gcc-4.9 which is needed.

**Comment by countgizmo** [comment]
Have you apt-get install’ed build-essentials?

**Comment by 6D65** [comment]
Tried a lot of stuff, that debian build I was using seems broken and overall a dead end. Will try to use other lightweight distros, but i'm not sure it will help, the tools themselves installed on the vm's are big.

Probably we could try to use docker, either as a provisioner for vagrant, or directly(http://kitematic.com), though again i'm not sure it will help. Probably will be a good idea to free up some space, or upgrade the laptop's storage.

Also there's this nice stackoverflow question(http://stackoverflow.com/questions/16647069/should-i-use-vagrant-or-docker-io-for-creating-an-isolated-environment) with answers from both Mitchell Hashimoto and Solomon Hykes, about when to use docker or vagrant. We might want later to have a CI system, so  docker may be an answer, the bash scripts can be reused to also provision a Docker image.
